[workspace]
resolver = "2" #needed to not bundle dev-dependencies into wasm builds
members = [  
  "libs/zomes/*",
  ]

[workspace.dependencies]
hdi = "0.2.0-beta-rc.1"
hdk = "0.1.0-beta-rc.1"

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"
