[workspace]
resolver = "2" #needed to not bundle dev-dependencies into wasm builds
members = [
  "dna/zomes/how",
  "dna/zomes/profiles"
  ]

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"
