# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-test:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # Checks out a copy of your repository on the ubuntu-latest machine


    - name: Fetch source code
      uses: actions/checkout@v3
    - name: Use Nix
      uses: cachix/install-nix-action@v22
    - name: Use cachix
      uses: cachix/cachix-action@v12
      with:
        name: holochain-ci
    - name: run-tests
      run: |
        nix develop  --command npm install
        nix develop  --command npm ci
        nix develop  --command npm run test
